name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/rust-tokio:amd64-latest #$(date +%s)
    - name: Push Docker image
      run: docker push ${{secrets.DOCKERHUB_USER}}/rust-tokio #:amd64-latest
